version: "3.8"

networks:
  web:
    external: true
  traefik_internal:
    external: true

volumes:
  web-root:
  node_modules:
  certbot-etc:
  certbot-var:

services:
  entity:
    build:
      context: .
      dockerfile: Dockerfile
    image: entity_image:latest
    container_name: traefik-entity-1
    restart: unless-stopped
    env_file: .env
    environment:
      - USER_GATEWAY_API_URL=$USER_GATEWAY_API_URL
      - INCIDENT_API_URL=$INCIDENT_API_URL
      - ENTITY_API_URL=$ENTITY_API_URL
      - BUDGETLINE_API_URL=${BUDGETLINE_API_URL}

    labels:
      - traefik.http.routers.entity.rule=Host(`entity.bfcgroupsa.com`)
      - traefik.http.routers.entity.tls=true
      - traefik.http.routers.entity.tls.certresolver=lets-encrypt
      - traefik.http.services.entity.loadbalancer.server.port=3000

    networks:
      - traefik_internal
      - web

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver-entity
    restart: unless-stopped
    volumes:
      - web-root:/var/www/html
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    depends_on:
      - entity
    networks:
      - traefik_internal
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot-entity
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email ysiaka@bfclimited.com --agree-tos --no-eff-email --staging -d entity.bfcgroupsa.com -d www.entity.bfcgroupsa.com