version: '3.8'

networks:
  web:
    external: true
  internal:
    external: true

services:
  entity:
    build:
      context: .
      dockerfile: Dockerfile
    image: entity_image:latest
    container_name: traefik-entity-1
    restart: unless-stopped
    env_file: .env
    environment:
      - USER_GATEWAY_API_URL=${USER_GATEWAY_API_URL}
      - INCIDENT_API_URL=${INCIDENT_API_URL}
      - ENTITY_API_URL=${ENTITY_API_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.entity.rule=Host(`entity.bfcgroupsa.com`)"
      - "traefik.http.routers.entity.entrypoints=websecure"
      - "traefik.http.routers.entity.tls=true"
      - "traefik.http.routers.entity.tls.certresolver=lets-encrypt"
      - "traefik.http.services.entity.loadbalancer.server.port=3000"
    networks:
      - internal
      - web